/* eslint-disable @typescript-eslint/no-explicit-any */
import {beforeEach,describe,expect,it,vi} from "vitest";
const m=vi.hoisted(()=>({context:null as any,role:"owner",allowed:true,nonce:"nonce-secure-value-1234567890",responses:[] as any[],calls:[] as any[],stateValid:true,exchangeError:false}));
vi.mock("next/headers",()=>({cookies:async()=>({get:()=>({value:m.nonce})})}));
vi.mock("@/lib/supabase/api-context",()=>({getApiContext:async()=>m.context}));
vi.mock("@/lib/rate-limit",()=>({consumeRateLimit:async()=>({allowed:m.allowed,retry_after:60})}));
vi.mock("@/lib/meta-oauth-state",()=>({createMetaOAuthState:()=>({state:"signed-state-value-with-enough-length",payload:{nonce:m.nonce}}),verifyMetaOAuthState:()=>m.stateValid?({userId:"user-a",organizationId:"org-a"}):null}));
vi.mock("@/lib/meta-token-crypto",()=>({encryptMetaToken:()=>"encrypted-test-value"}));
vi.mock("@/lib/meta-assets",()=>({exchangeMetaCode:async()=>{if(m.exchangeError)throw new Error("META_TOKEN_190");return{access_token:"server-only-token",expires_in:3600}},validateWhatsAppAssets:async()=>({waba:{id:"22222",name:"WABA",currency:"CLP"},phone:{id:"33333",verified_name:"Empresa",display_phone_number:"+56",quality_rating:"GREEN"}}),subscribeWaba:async()=>true}));
vi.mock("@/lib/structured-log",()=>({operationalLog:vi.fn()}));
vi.mock("@/lib/supabase/admin",()=>({createAdminClient:()=>({rpc:(name:string,args:any)=>{m.calls.push(["rpc",name,args]);const result=m.responses.shift()??{data:true,error:null};return{single:async()=>result,then:(resolve:any)=>resolve(result)}},from:(table:string)=>{const b:any={};for(const method of ["insert","upsert","select","single"]){b[method]=(...args:any[])=>{m.calls.push([table,method,...args]);if(method==="single")return Promise.resolve(m.responses.shift()??{data:null,error:null});return b}}b.then=(resolve:any)=>resolve(m.responses.shift()??{data:null,error:null});return b}})}));
import {GET,POST} from "@/app/api/meta/embedded-signup/session/route";
function request(body:any,headers={origin:"https://estructuradigital.cl",host:"estructuradigital.cl","content-type":"application/json"}){return new Request("https://estructuradigital.cl/api/meta/embedded-signup/session",{method:"POST",headers,body:JSON.stringify(body)})}
const valid={code:"temporary-code-value",business_id:"11111",waba_id:"22222",phone_number_id:"33333",session_id:"11111111-1111-4111-8111-111111111111",state:"signed-state-value-with-enough-length",nonce:"nonce-secure-value-1234567890"};
describe("Embedded Signup session",()=>{beforeEach(()=>{m.context={user:{id:"user-a"},organizationId:"org-a",role:"owner"};m.allowed=true;m.responses=[];m.calls=[];m.stateValid=true;m.exchangeError=false});it("exige autenticación y rol privilegiado al iniciar",async()=>{m.context=null;expect((await GET()).status).toBe(401);m.context={user:{id:"u"},organizationId:"o",role:"viewer"};expect((await GET()).status).toBe(403)});it("crea state, nonce persistente y cookie segura",async()=>{m.responses.push({error:null});const r=await GET();expect(r.status).toBe(200);expect(await r.json()).toMatchObject({nonce:m.nonce});const cookie=r.headers.get("set-cookie")||"";expect(cookie).toContain("HttpOnly");expect(cookie).toContain("Secure");expect(m.calls.some(c=>c[0]==="oauth_nonces")).toBe(true)});it("aplica rate limit",async()=>{m.allowed=false;expect((await GET()).status).toBe(429)});it("rechaza CSRF, payload inválido y nonce consumido",async()=>{expect((await POST(request(valid,{origin:"https://evil.example",host:"estructuradigital.cl","content-type":"application/json"}))).status).toBe(403);expect((await POST(request({...valid,business_id:"bad/path"}))).status).toBe(400);m.responses.push({data:false});expect((await POST(request(valid))).status).toBe(409)});it("rechaza state inválido y sanitiza fallos de canje",async()=>{m.stateValid=false;expect((await POST(request(valid))).status).toBe(401);m.stateValid=true;m.exchangeError=true;m.responses.push({data:true});const r=await POST(request(valid));expect(r.status).toBe(502);expect(JSON.stringify(await r.json())).not.toContain("190")});it("conecta y persiste de forma idempotente",async()=>{m.responses.push({data:true},{data:{id:"integration-a"},error:null},{error:null},{error:null});const r=await POST(request(valid));expect(r.status).toBe(200);expect(await r.json()).toMatchObject({status:"connected"});expect(m.calls.some(c=>c[0]==="integration_accounts"&&c[1]==="upsert"&&c[3]?.onConflict==="organization_id,waba_id,phone_number_id")).toBe(true);expect(r.headers.get("set-cookie")).toContain("Max-Age=0")})});