import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {exchangeMetaCode,subscribeWaba,unsubscribeWaba,validateWhatsAppAssets} from "@/lib/meta-assets";
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}})}
describe("Meta Graph assets",()=>{beforeEach(()=>{process.env.META_BUSINESS_APP_ID="business-app";process.env.META_BUSINESS_APP_SECRET="test-secret-not-real";process.env.META_GRAPH_API_VERSION="v26.0"});afterEach(()=>vi.unstubAllGlobals());
it("canjea el código por POST sin secretos en URL",async()=>{const fetchMock=vi.fn().mockResolvedValue(json({access_token:"test-token",expires_in:3600}));vi.stubGlobal("fetch",fetchMock);const result=await exchangeMetaCode("temporary-code");expect(result.expires_in).toBe(3600);const[url,init]=fetchMock.mock.calls[0];expect(url).not.toContain("client_secret");expect(init.method).toBe("POST");expect(String(init.body)).toContain("client_secret=")});
it("falla cerrado sin credenciales",async()=>{delete process.env.META_BUSINESS_APP_ID;delete process.env.META_BUSINESS_APP_SECRET;delete process.env.META_APP_ID;delete process.env.META_APP_SECRET;await expect(exchangeMetaCode("x")).rejects.toThrow("META_CREDENTIALS_MISSING")});
it("valida que el teléfono pertenezca a la WABA",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json({id:"waba",name:"Empresa"})).mockResolvedValueOnce(json({id:"phone",verified_name:"Estructura"})).mockResolvedValueOnce(json({data:[{id:"phone"}]}));vi.stubGlobal("fetch",fetchMock);const result=await validateWhatsAppAssets("token",{businessId:"business",wabaId:"waba",phoneNumberId:"phone"});expect(result.phone.id).toBe("phone");expect(fetchMock.mock.calls.every(([url])=>!String(url).includes("/me/businesses"))).toBe(true)});
it("rechaza una WABA incompatible",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(json({id:"waba"})).mockResolvedValueOnce(json({id:"phone"})).mockResolvedValueOnce(json({data:[{id:"other"}]})));await expect(validateWhatsAppAssets("token",{businessId:"business",wabaId:"waba",phoneNumberId:"phone"})).rejects.toThrow("META_ASSET_MISMATCH")});
it("suscribe y confirma la aplicación de forma idempotente",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json({success:true})).mockResolvedValueOnce(json({data:[{id:"business-app"}]}));vi.stubGlobal("fetch",fetchMock);await expect(subscribeWaba("waba","token")).resolves.toBe(true);expect(fetchMock.mock.calls[0][1].method).toBe("POST")});
it("detecta una suscripción ausente",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(json({success:true})).mockResolvedValueOnce(json({data:[]})));await expect(subscribeWaba("waba","token")).rejects.toThrow("META_SUBSCRIPTION_MISSING")});
it("desuscribe con DELETE y sanitiza errores Graph",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(json({success:true})).mockResolvedValueOnce(json({error:{code:190,message:"sensitive"}},401));vi.stubGlobal("fetch",fetchMock);await unsubscribeWaba("waba","token");expect(fetchMock.mock.calls[0][1].method).toBe("DELETE");await expect(unsubscribeWaba("waba","token")).rejects.toThrow("META_GRAPH_190");await expect(unsubscribeWaba("waba","token")).rejects.not.toThrow("sensitive")})});