/* eslint-disable @typescript-eslint/no-explicit-any */
import {beforeEach,describe,expect,it,vi} from "vitest";
const m=vi.hoisted(()=>({context:null as any,allowed:true,calls:[] as any[]}));
vi.mock("@/lib/supabase/api-context",()=>({getApiContext:async()=>m.context}));
vi.mock("@/lib/rate-limit",()=>({consumeRateLimit:async()=>({allowed:m.allowed})}));
vi.mock("@/lib/structured-log",()=>({operationalLog:vi.fn()}));
vi.mock("@/lib/supabase/admin",()=>({createAdminClient:()=>({from:(table:string)=>{const b:any={};for(const method of ["select","eq","single","delete"]){b[method]=(...args:any[])=>{m.calls.push([table,method,...args]);if(method==="single")return Promise.resolve({data:{name:"Org"},error:null});return b}}b.then=(resolve:any)=>resolve({data:null,error:null});return b}})}));
import {POST} from "@/app/api/organization/invitations/route";
function context(role="owner"){return{user:{id:"user-a"},organizationId:"org-a",role,supabase:{rpc:async()=>({data:"11111111-1111-4111-8111-111111111111",error:null})}}}
function request(body:any,origin="https://estructuradigital.cl"){return new Request("https://estructuradigital.cl/api/organization/invitations",{method:"POST",headers:{origin,host:"estructuradigital.cl","content-type":"application/json"},body:JSON.stringify(body)})}
describe("member invitations",()=>{beforeEach(()=>{m.context=context();m.allowed=true;m.calls=[];delete process.env.RESEND_API_KEY});it("exige origen, sesión y rol",async()=>{expect((await POST(request({email:"a@example.com",role:"viewer"},"https://evil.example"))).status).toBe(403);m.context=null;expect((await POST(request({email:"a@example.com",role:"viewer"}))).status).toBe(401);m.context=context("viewer");expect((await POST(request({email:"a@example.com",role:"viewer"}))).status).toBe(403)});it("valida email y restricciones de Admin",async()=>{expect((await POST(request({email:"bad",role:"owner"}))).status).toBe(400);m.context=context("admin");expect((await POST(request({email:"a@example.com",role:"admin"}))).status).toBe(403)});it("aplica rate limit",async()=>{m.allowed=false;expect((await POST(request({email:"a@example.com",role:"viewer"}))).status).toBe(429)});it("no afirma éxito ni conserva fila si falta correo",async()=>{const r=await POST(request({email:"a@example.com",role:"agent"}));expect(r.status).toBe(503);expect(m.calls.some(c=>c[0]==="organization_invitations"&&c[1]==="delete")).toBe(true)})});