/* eslint-disable @typescript-eslint/no-explicit-any */
import {beforeEach,describe,expect,it,vi} from "vitest";
const m=vi.hoisted(()=>({context:null as any,rates:[{allowed:true},{allowed:true}] as any[],config:{version:"v26.0",phoneNumberId:"33333",accessToken:"server-token",wabaId:"22222"} as any,configError:false,calls:[] as any[]}));
vi.mock("@/lib/supabase/api-context",()=>({getApiContext:async()=>m.context}));
vi.mock("@/lib/rate-limit",()=>({consumeRateLimit:async()=>m.rates.shift()??{allowed:true}}));
vi.mock("@/lib/whatsapp-organization-config",()=>({getOrganizationWhatsAppConfig:async()=>{if(m.configError)throw new Error("WHATSAPP_NOT_CONNECTED");return m.config}}));
vi.mock("@/lib/structured-log",()=>({operationalLog:vi.fn()}));
import {POST} from "@/app/api/whatsapp/send/route";
function supabase(){return{from:(table:string)=>{const b:any={};for(const method of ["upsert","select","single","insert"]){b[method]=(...args:any[])=>{m.calls.push([table,method,...args]);if(method==="single")return Promise.resolve({data:{id:`${table}-id`},error:null});return b}}b.then=(resolve:any)=>resolve({data:null,error:null});return b}}}
function req(body:any,origin="https://estructuradigital.cl"){return new Request("https://estructuradigital.cl/api/whatsapp/send",{method:"POST",headers:{origin,host:"estructuradigital.cl","content-type":"application/json"},body:JSON.stringify(body)})}
const valid={to:"56912345678",message:"PRUEBA ESTRUCTURA DIGITAL"};
describe("WhatsApp send route",()=>{beforeEach(()=>{m.context={user:{id:"user-a"},organizationId:"org-a",role:"owner",supabase:supabase()};m.rates=[{allowed:true},{allowed:true}];m.configError=false;m.calls=[];vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({messages:[{id:"wamid-test"}]}),{status:200})))});it("rechaza CSRF, anónimo y rol no autorizado",async()=>{expect((await POST(req(valid,"https://evil.example"))).status).toBe(403);m.context=null;expect((await POST(req(valid))).status).toBe(401);m.context={user:{id:"u"},organizationId:"o",role:"viewer",supabase:supabase()};expect((await POST(req(valid))).status).toBe(403)});it("limita por usuario u organización",async()=>{m.rates=[{allowed:false},{allowed:true}];expect((await POST(req(valid))).status).toBe(429)});it("valida payload y conexión por organización",async()=>{expect((await POST(req({to:"+56",message:""}))).status).toBe(400);m.configError=true;expect((await POST(req(valid))).status).toBe(503)});it("sanitiza rechazo Graph",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({error:{message:"detalle sensible",code:190}}),{status:401})));const r=await POST(req(valid));expect(r.status).toBe(401);expect(JSON.stringify(await r.json())).not.toContain("detalle sensible")});it("envía plantilla Utility con el tenant activo",async()=>{const template={type:"template",to:"56912345678",templateName:"confirmacion_solicitud",languageCode:"es",parameters:["Sebastián","Estructura Digital"]};const r=await POST(req(template));expect(r.status).toBe(200);const payload=JSON.parse((fetch as any).mock.calls[0][1].body);expect(payload).toMatchObject({type:"template",template:{name:"confirmacion_solicitud",language:{code:"es"}}});expect(m.calls.some(c=>c[0]==="messages"&&c[1]==="insert"&&c[2].body.includes("recibimos tu solicitud"))).toBe(true);expect(m.calls.some(c=>c[0]==="integrations"||c[0]==="integration_accounts")).toBe(false)});it("envía y persiste mensaje aislado por organización",async()=>{const r=await POST(req(valid));expect(r.status).toBe(200);expect(await r.json()).toMatchObject({status:"sent"});expect(m.calls.some(c=>c[0]==="messages"&&c[1]==="insert"&&c[2].organization_id==="org-a")).toBe(true);expect((fetch as any).mock.calls[0][0]).toContain("/33333/messages");expect((fetch as any).mock.calls[0][1].headers.Authorization).toContain("server-token")})});