import type { ServiceLandingProps } from "@/components/service-landing";

const commonProcess = [
  { title: "Diagnóstico", description: "Revisamos objetivo, público, operación actual y restricciones." },
  { title: "Propuesta", description: "Definimos alcance, prioridades, entregables y etapas." },
  { title: "Implementación", description: "Construimos, integramos y validamos contigo." },
  { title: "Lanzamiento", description: "Publicamos, medimos y dejamos una base mantenible." },
];

export const commercialServices: Record<string, ServiceLandingProps> = {
  websites: {
    eyebrow: "Páginas web para empresas",
    title: "Tu página web informativa desde $49.990.",
    description: "Creamos páginas informativas simples y rápidas, además de tiendas iniciales con carrito desde $89.990. Cada plan tiene un alcance claro para comenzar sin costos inesperados.",
    serviceName: "Página web para empresa",
    cta: "Solicitar mi página web",
    outcomes: ["Presentar tu empresa con credibilidad", "Convertir visitas en consultas comerciales", "Aparecer en búsquedas relevantes", "Medir formularios, llamadas y contactos"],
    deliverables: ["Estrategia y estructura de contenidos", "Diseño adaptable a móvil y escritorio", "Desarrollo optimizado para velocidad", "SEO técnico y datos estructurados", "Formulario y canales de contacto", "Analítica y eventos de conversión"],
    process: commonProcess,
    idealFor: ["Empresas que aún no tienen una web profesional", "Negocios con una web que no genera consultas", "Servicios B2B que necesitan explicar mejor su propuesta", "Empresas que quieren comenzar con SEO o Google Ads"],
    faqs: [
      { question: "¿Cuánto cuesta crear una página web?", answer: "Depende de la cantidad de páginas, contenidos, integraciones y funciones. Después de una breve reunión entregamos un alcance y una cotización por etapas." },
      { question: "¿La página queda optimizada para Google?", answer: "Sí. Trabajamos estructura, velocidad, metadatos, indexación, datos estructurados y medición. El posicionamiento orgánico posterior también depende de autoridad y contenidos." },
      { question: "¿Pueden trabajar con mi dominio actual?", answer: "Sí. Podemos mantener el dominio y coordinar la publicación reduciendo el impacto sobre correos y servicios existentes." },
    ],
  },
  design: {
    eyebrow: "Diseño web en Chile",
    title: "Diseño web profesional que explica, diferencia y convierte.",
    description: "Diseñamos experiencias web claras para empresas que necesitan transmitir confianza, ordenar su oferta y facilitar el contacto desde cualquier dispositivo.",
    serviceName: "Diseño web profesional",
    cta: "Solicitar propuesta",
    outcomes: ["Una identidad digital coherente", "Jerarquía de contenidos fácil de entender", "Mejor experiencia en dispositivos móviles", "Llamadas a la acción visibles y medibles"],
    deliverables: ["Arquitectura de información", "Dirección visual alineada con la marca", "Diseño responsive", "Componentes reutilizables", "Prototipo y validación", "Implementación lista para publicar"],
    process: commonProcess,
    idealFor: ["Marcas que necesitan renovar su presencia digital", "Empresas con servicios difíciles de explicar", "Equipos que requieren una web escalable", "Negocios que preparan campañas de adquisición"],
    faqs: [
      { question: "¿Diseñan y también desarrollan la web?", answer: "Sí. Podemos encargarnos del proceso completo, desde la arquitectura y el contenido hasta el desarrollo y la publicación." },
      { question: "¿El diseño funciona en celulares?", answer: "Sí. Cada página se diseña y prueba para móvil, tablet y escritorio, priorizando legibilidad y facilidad de contacto." },
      { question: "¿Pueden respetar nuestra identidad de marca?", answer: "Sí. Trabajamos con los recursos existentes o definimos un sistema visual digital coherente cuando la marca aún no dispone de uno." },
    ],
  },
  landing: {
    eyebrow: "Landing pages en Chile",
    title: "Landing pages diseñadas para convertir campañas en oportunidades.",
    description: "Creamos páginas enfocadas en una oferta, un público y una acción concreta, con velocidad, medición y mensajes alineados con tus anuncios.",
    serviceName: "Landing page para campañas",
    cta: "Cotizar landing page",
    outcomes: ["Mayor coherencia entre anuncio y página", "Menos distracciones antes del contacto", "Medición precisa de conversiones", "Base rápida para probar ofertas"],
    deliverables: ["Estructura de conversión", "Copy orientado al cliente", "Diseño responsive", "Formulario o contacto directo", "Analítica y conversiones", "Integración con Google Ads"],
    process: commonProcess,
    idealFor: ["Campañas de Google Ads", "Lanzamiento de un servicio", "Validación de una oferta", "Captación de prospectos para ventas"],
    faqs: [
      { question: "¿Qué diferencia una landing page de una página web?", answer: "Una landing se enfoca en una sola oferta y acción. Una web corporativa presenta la empresa y varias líneas de servicio." },
      { question: "¿Incluye seguimiento de conversiones?", answer: "Sí. Podemos medir formularios, llamadas y clics relevantes para evaluar la campaña con datos reales." },
      { question: "¿Puede usarse con Google Ads?", answer: "Sí. Se prepara para mantener coherencia con los anuncios, cargar rápido y registrar las acciones que importan." },
    ],
  },
  software: {
    eyebrow: "Software a medida",
    title: "Software construido alrededor de tu forma de trabajar.",
    description: "Desarrollamos sistemas web, paneles y herramientas internas para reemplazar planillas dispersas, procesos manuales y soluciones que ya no acompañan el crecimiento.",
    serviceName: "Software a medida",
    cta: "Evaluar mi proyecto",
    outcomes: ["Procesos centralizados y trazables", "Menos errores y trabajo duplicado", "Permisos y responsabilidades claras", "Información útil para tomar decisiones"],
    deliverables: ["Levantamiento del proceso", "Diseño funcional y técnico", "Aplicación web responsive", "Usuarios, roles y permisos", "Integraciones y migración", "Pruebas, documentación y soporte"],
    process: commonProcess,
    idealFor: ["Empresas que dependen de múltiples planillas", "Operaciones con reglas y excepciones propias", "Equipos que necesitan trazabilidad", "Negocios que quieren digitalizar un servicio"],
    faqs: [
      { question: "¿Cuándo conviene software a medida?", answer: "Cuando el proceso es estratégico, tiene reglas propias o las herramientas existentes obligan a mantener trabajo manual y datos fragmentados." },
      { question: "¿Se puede construir por etapas?", answer: "Sí. Recomendamos priorizar un primer módulo útil, validarlo con usuarios y ampliar sobre una base estable." },
      { question: "¿Integran sistemas existentes?", answer: "Sí, cuando disponen de APIs, webhooks u otros mecanismos autorizados. La factibilidad se valida durante el diagnóstico." },
    ],
  },
  automation: {
    eyebrow: "Automatización de procesos",
    title: "Automatiza tareas repetitivas sin perder control de la operación.",
    description: "Conectamos sistemas, datos y responsables para reducir trabajo manual, acelerar respuestas y dejar trazabilidad en cada etapa.",
    serviceName: "Automatización de procesos",
    cta: "Detectar oportunidades",
    outcomes: ["Menos tareas manuales", "Respuestas y avisos oportunos", "Datos consistentes entre herramientas", "Excepciones críticas bajo supervisión"],
    deliverables: ["Mapa del proceso actual", "Identificación de tareas automatizables", "Flujos y reglas", "Integraciones autorizadas", "Alertas y registro de eventos", "Monitoreo y plan de continuidad"],
    process: commonProcess,
    idealFor: ["Procesos con copiar y pegar frecuente", "Seguimientos que dependen de recordatorios manuales", "Datos repetidos en varias plataformas", "Equipos con alto volumen de solicitudes"],
    faqs: [
      { question: "¿Qué procesos se pueden automatizar?", answer: "Ingreso y validación de datos, notificaciones, asignaciones, actualización de estados, generación de documentos y sincronización entre sistemas, entre otros." },
      { question: "¿La automatización reemplaza a las personas?", answer: "No necesariamente. Normalmente elimina tareas repetitivas y mantiene revisión humana en decisiones o excepciones importantes." },
      { question: "¿Pueden automatizar herramientas que ya usamos?", answer: "Sí, si ofrecen accesos técnicos autorizados. Primero validamos seguridad, límites y continuidad del flujo." },
    ],
  },
  crm: {
    eyebrow: "CRM para pymes",
    title: "Un CRM adaptado a tu proceso comercial, no al revés.",
    description: "Organizamos contactos, oportunidades, tareas y conversaciones para que tu equipo sepa qué ocurrió, qué sigue y quién es responsable.",
    serviceName: "CRM para pymes",
    cta: "Evaluar CRM",
    outcomes: ["Clientes e historial en un solo lugar", "Seguimiento consistente de oportunidades", "Responsables y próximas acciones visibles", "Métricas comerciales comprensibles"],
    deliverables: ["Diseño de etapas comerciales", "Configuración o desarrollo del CRM", "Importación inicial de datos", "Automatizaciones y recordatorios", "Paneles y reportes", "Capacitación y acompañamiento"],
    process: commonProcess,
    idealFor: ["Pymes que gestionan ventas en planillas", "Equipos con oportunidades sin seguimiento", "Empresas con información dispersa", "Negocios que necesitan integrar atención y ventas"],
    faqs: [
      { question: "¿Implementan un CRM existente o desarrollan uno?", answer: "Evaluamos ambas alternativas. Si una herramienta disponible cubre el proceso, la configuramos; si existen reglas específicas, podemos desarrollar módulos a medida." },
      { question: "¿Pueden importar nuestros contactos?", answer: "Sí. Primero revisamos calidad, estructura, consentimiento y duplicados para planificar una migración controlada." },
      { question: "¿Incluye capacitación?", answer: "Sí. La adopción del equipo es parte de la implementación y se acompaña con documentación y sesiones según el alcance." },
    ],
  },
  whatsapp: {
    eyebrow: "CRM con WhatsApp",
    title: "Conecta WhatsApp con el seguimiento comercial de tu empresa.",
    description: "Integramos conversaciones autorizadas con contactos, responsables, tareas y estados para reducir pérdidas de contexto y mejorar la continuidad de atención.",
    serviceName: "CRM con WhatsApp",
    cta: "Revisar integración",
    outcomes: ["Conversaciones asociadas al cliente", "Seguimiento compartido entre responsables", "Tareas y estados después de cada contacto", "Uso de canales oficiales y trazables"],
    deliverables: ["Revisión del flujo de atención", "Configuración del canal oficial", "Vinculación con contactos y oportunidades", "Plantillas y reglas autorizadas", "Asignación y seguimiento", "Pruebas y documentación operativa"],
    process: commonProcess,
    idealFor: ["Equipos que atienden desde varios teléfonos", "Ventas que comienzan o continúan por WhatsApp", "Empresas con pérdida de contexto entre agentes", "Negocios que necesitan métricas de atención"],
    faqs: [
      { question: "¿La integración usa canales oficiales?", answer: "Sí. Trabajamos con mecanismos autorizados y la factibilidad depende de las políticas, permisos y aprobaciones aplicables." },
      { question: "¿Se pueden automatizar mensajes?", answer: "Sí, dentro de las reglas del canal y manteniendo supervisión cuando corresponda. El diseño evita automatizaciones indiscriminadas." },
      { question: "¿Funciona con un CRM que ya utilizamos?", answer: "Depende de las capacidades de integración del CRM. Lo validamos antes de comprometer alcance y plazos." },
    ],
  },
};
