import Link from "next/link";
import { ArrowRight, Bot, CalendarCheck, Check, ClipboardCheck, Headphones, MessageSquareReply, ShieldCheck, Sparkles } from "lucide-react";
import { formatPlanPrice, plans, safetyConfig } from "@/lib/site-config";

const employees=[
 {name:"Recepcionista IA",icon:Headphones,goal:"Recibe cada consulta y ordena el siguiente paso.",capabilities:["Responde preguntas","Recopila datos","Deriva excepciones"],status:"Disponible"},
 {name:"Ejecutivo Comercial IA",icon:Sparkles,goal:"Convierte necesidades en una propuesta clara.",capabilities:["Recomienda servicios","Calcula precios","Genera cotizaciones"],status:"Disponible"},
 {name:"Agendador IA",icon:CalendarCheck,goal:"Coordina reservas según tus reglas.",capabilities:["Consulta disponibilidad","Propone horarios","Evita conflictos"],status:"Disponible"},
 {name:"Seguimiento IA",icon:MessageSquareReply,goal:"Retoma oportunidades que requieren atención.",capabilities:["Recuerda solicitudes","Retoma cotizaciones","Detecta pendientes"],status:"Piloto"},
 {name:"Postventa IA",icon:ClipboardCheck,goal:"Clasifica consultas posteriores y reúne contexto.",capabilities:["Recibe antecedentes","Clasifica problemas","Deriva casos sensibles"],status:"Próximamente"},
];
const faqs=[
 ["¿Qué es un empleado de IA?","Es una configuración especializada para ejecutar tareas concretas con reglas, límites y supervisión de tu equipo."],
 ["¿Qué canales utiliza?","El piloto funciona en el simulador y la bandeja. Los canales externos sólo se activan cuando tú los autorizas y completas su conexión."],
 ["¿Puede cometer errores?","Sí. Por eso Elytsa muestra trazabilidad, límites y derivación humana para revisar decisiones sensibles."],
 ["¿Cuándo deriva a una persona?","Cuando una regla lo exige, faltan datos, existe una excepción o la confianza de la respuesta no es suficiente."],
 ["¿Cómo calcula precios?","Usa el catálogo, variantes, extras y reglas que tu empresa revisa antes de activar."],
 ["¿Cómo se protege la información?","Cada organización tiene acceso separado, permisos, auditoría y controles de presupuesto y canales."],
 ["¿Qué pasa si supero el límite?","Se detiene o reduce el uso según el plan y te avisamos para revisar capacidad; no prometemos uso ilimitado."],
 ["¿Necesito conocimientos técnicos?","No. El onboarding guía la configuración y deja cada propuesta lista para revisión."],
 ["¿Cuánto demora la configuración?","Depende de la cantidad de servicios y reglas. Un piloto acotado puede prepararse en una sesión."],
 ["¿Cómo cancelo?","Podrás solicitar la cancelación desde tu cuenta. Las condiciones definitivas se confirmarán en los términos antes del lanzamiento."],
];
export default function HomePage(){return <>
<section className="elytsa-hero section"><div className="container hero-grid"><div><p className="eyebrow">Empleados de IA para empresas de servicios</p><h1>Tu equipo crece.<br/><span>Tu atención también.</span></h1><p className="lead">Elytsa incorpora empleados de IA que atienden, cotizan, agendan y hacen seguimiento, con las reglas y el control de tu empresa.</p><div className="button-row"><Link className="button button-primary" href="/registro">Crear mi empleado de IA <ArrowRight size={18}/></Link><Link className="button button-secondary" href="#demo">Ver cómo funciona</Link></div><p className="hero-note"><ShieldCheck size={16}/> Comienza en modo simulado. Nada se envía a clientes sin tu autorización.</p></div><div className="conversation-demo" id="demo" aria-label="Demostración simulada de Elytsa"><div className="demo-head"><span className="demo-avatar"><Bot size={18}/></span><div><strong>Recepcionista Elytsa</strong><small>Demostración controlada</small></div><span className="demo-live">SIMULADO</span></div><div className="bubble client">Necesito limpieza para un departamento de 2 dormitorios.</div><div className="demo-thinking"><span/> Elytsa consulta servicios, zonas y reglas</div><div className="bubble ai">Puedo cotizarlo. ¿Está en Providencia y necesitas incluir horno?</div><div className="demo-result"><Check size={17}/><div><strong>Cotización preparada</strong><small>Luego ofrece disponibilidad, agenda y registra el historial.</small></div></div></div></div></section>
<section className="proof-strip"><div className="container">{["Responde más rápido","Atiende fuera de horario","Recupera oportunidades","Deriva casos complejos"].map(x=><span key={x}><Check size={16}/>{x}</span>)}</div></section>
<section className="section" id="producto"><div className="container"><p className="eyebrow">Un rol claro para cada trabajo</p><h2>Incorpora el empleado que hoy le falta a tu operación.</h2><div className="employee-grid">{employees.map(({name,icon:Icon,goal,capabilities,status})=><article className="employee-card" key={name}><div className="employee-top"><Icon/><span>{status}</span></div><h3>{name}</h3><p>{goal}</p><ul>{capabilities.map(c=><li key={c}><Check size={15}/>{c}</li>)}</ul></article>)}</div></div></section>
<section className="section process-section" id="como-funciona"><div className="container process-grid"><div><p className="eyebrow">Cómo funciona</p><h2>Tu operación primero. La IA después.</h2><p className="lead">Elytsa aprende de la información que tú apruebas y conserva una salida humana para las excepciones.</p></div><ol className="process-list">{["Describe tu empresa","Configura servicios y reglas","Activa tus empleados de IA","Revisa conversaciones, cotizaciones y reservas"].map((x,i)=><li key={x}><span>0{i+1}</span><strong>{x}</strong></li>)}</ol></div></section>
<section className="section use-cases"><div className="container"><p className="eyebrow">Diseñado para servicios</p><h2>Más continuidad comercial, sin sumar complejidad.</h2><div className="case-tags">{["Limpieza","Talleres","Estética","Mantenimiento","Salud no clínica","Educación","Servicios domiciliarios","Arriendos","Empresas técnicas"].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="section product-window"><div className="container"><div className="window-copy"><p className="eyebrow">Control real</p><h2>Todo queda visible para tu equipo.</h2><p>Una bandeja conecta solicitudes, cotizaciones, agenda, empleados IA, métricas y derivación humana sin ocultar cuándo interviene el proveedor simulado.</p></div><div className="mini-dashboard"><aside><strong>elytsa</strong>{["Bandeja","Solicitudes","Cotizaciones","Agenda","Empleados IA","Métricas"].map(x=><span key={x}>{x}</span>)}</aside><main><div className="mini-title"><span>Conversaciones</span><b>12 activas</b></div>{["Cotización preparada","Horario confirmado","Derivación solicitada"].map((x,i)=><article key={x}><span className="demo-avatar">{i+1}</span><div><strong>{x}</strong><small>Registro trazable · revisión disponible</small></div></article>)}</main></div></div></section>
<section className="section security-section"><div className="container"><p className="eyebrow">Seguridad y control</p><h2>Automatiza con límites claros.</h2><div className="security-grid">{["Separación por organización","Roles y permisos","Auditoría de acciones","Presupuestos de IA","Intervención humana","Canales externos controlados"].map(x=><div key={x}><ShieldCheck/><strong>{x}</strong></div>)}</div></div></section>
<section className="section" id="precios"><div className="container"><p className="eyebrow">Precios simples</p><h2>Empieza pequeño. Amplía cuando genere valor.</h2><p className="pricing-note">Valores mensuales en CLP, más impuestos cuando corresponda. Aplican límites de uso razonable.</p><div className="pricing-grid">{plans.map(p=><article className={"pricing-card "+("featured" in p&&p.featured?"featured":"")} key={p.id}>{"featured" in p&&p.featured&&<span className="recommended">Recomendado</span>}<h3>{p.name}</h3><p className="price"><small>{"pricePrefix" in p?p.pricePrefix:""}</small>{formatPlanPrice(p)}<em>/mes</em></p><p>{p.limits}</p><ul>{p.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Link className="button button-primary" href={p.id==="empresa"?"mailto:contacto@elytsa.com":"/registro"}>{p.cta}</Link></article>)}</div></div></section>
<section className="section faq-section" id="preguntas"><div className="container faq-grid"><div><p className="eyebrow">Preguntas frecuentes</p><h2>Lo importante, antes de comenzar.</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="section"><div className="container cta"><div><p className="eyebrow">Primer empleado</p><h2>Configúralo, pruébalo y revísalo antes de activarlo.</h2><p>{safetyConfig.llmProvider==="simulated"?"El entorno actual usa un proveedor simulado y mantiene bloqueados los envíos externos.":"Revisa el proveedor y los límites antes de activar."}</p></div><Link className="button button-light" href="/registro">Probar Elytsa <ArrowRight size={18}/></Link></div></section>
</>}
