/* eslint-disable @typescript-eslint/no-explicit-any -- injected fluent Supabase client */
import {buildAgentContext} from "@/domain/agents/context";
import {createLlmProvider} from "@/domain/agents/provider-factory";
import {assertUsageBudget,estimateLlmCost} from "@/domain/agents/budget";
type Db={from:(table:string)=>any};
export async function runServiceAgent(input:{db:Db;organizationId:string;agentId:string;message:string;serviceRequestId?:string;conversationId?:string;idempotencyKey:string}){
 const agent=await input.db.from("service_agents").select("*,service_agent_versions(*)").eq("organization_id",input.organizationId).eq("id",input.agentId).eq("active",true).maybeSingle();if(!agent.data)throw new Error("AGENT_NOT_ACTIVE");
 const version=(agent.data.service_agent_versions as Array<Record<string,any>>).find(v=>v.id===agent.data.active_version_id);if(!version)throw new Error("ACTIVE_VERSION_MISSING");
 if(input.serviceRequestId){const handoff=await input.db.from("human_handoffs").select("id").eq("organization_id",input.organizationId).eq("service_request_id",input.serviceRequestId).in("status",["OPEN","CLAIMED"]).limit(1);if(handoff.data?.length)throw new Error("AI_PAUSED_BY_HANDOFF")}
 const existing=await input.db.from("agent_tool_calls").select("agent_run_id,output,status").eq("organization_id",input.organizationId).eq("idempotency_key",input.idempotencyKey).maybeSingle();if(existing.data?.status==="SUCCEEDED")return{idempotent:true,runId:existing.data.agent_run_id,result:existing.data.output};
 const settingsResult=await input.db.from("organization_pilot_settings").select("*").eq("organization_id",input.organizationId).maybeSingle();const settings=settingsResult.data??{llm_provider:"simulated",llm_model:"simulated-service-agent-v1",llm_enabled:false,monthly_token_budget:100000,monthly_cost_budget:10,per_run_token_limit:4000};const month=new Date();month.setUTCDate(1);month.setUTCHours(0,0,0,0);const usage=await input.db.from("agent_runs").select("input_tokens,output_tokens,estimated_cost").eq("organization_id",input.organizationId).gte("created_at",month.toISOString());const used=(usage.data??[]).reduce((a:any,r:any)=>({tokens:a.tokens+Number(r.input_tokens||0)+Number(r.output_tokens||0),cost:a.cost+Number(r.estimated_cost||0)}),{tokens:0,cost:0});assertUsageBudget({monthlyTokenBudget:Number(settings.monthly_token_budget),monthlyCostBudget:Number(settings.monthly_cost_budget),perRunTokenLimit:Number(settings.per_run_token_limit),usedTokens:used.tokens,usedCost:used.cost});
 const provider=createLlmProvider({provider:settings.llm_provider,model:settings.llm_model,enabled:Boolean(settings.llm_enabled)});const run=await input.db.from("agent_runs").insert({organization_id:input.organizationId,agent_id:input.agentId,agent_version_id:version.id,service_request_id:input.serviceRequestId,conversation_id:input.conversationId,status:"RUNNING",provider:settings.llm_provider,model:settings.llm_model}).select("id").single();if(!run.data)throw new Error("RUN_CREATE_FAILED");
 try{const layers=buildAgentContext({policy:"Nunca inventes precios ni disponibilidad. Detente ante handoff.",profile:"Empresa de servicios",agentVersion:`v${version.version}: ${version.instructions}`,catalog:"Usa herramientas autorizadas",recentMessages:[input.message]});const result=await provider.complete({systemLayers:layers,customerText:input.message,timeoutMs:15000});if(result.inputTokens+result.outputTokens>Number(settings.per_run_token_limit))throw new Error("RUN_TOKEN_LIMIT_EXCEEDED");const action=result.response.nextAction;const tool=action==="prepare_quote"?"calculate_quote":action==="offer_schedule"?"find_slots":action==="transfer_to_human"?"request_handoff":null;if(tool&&!version.allowed_tools.includes(tool))throw new Error("TOOL_NOT_ALLOWED");if(tool)await input.db.from("agent_tool_calls").insert({organization_id:input.organizationId,agent_run_id:run.data.id,tool_name:tool,idempotency_key:input.idempotencyKey,input:{action},output:{simulated:settings.llm_provider==="simulated"},status:"SUCCEEDED",completed_at:new Date().toISOString()});if(tool==="request_handoff"&&input.serviceRequestId)await input.db.from("human_handoffs").insert({organization_id:input.organizationId,service_request_id:input.serviceRequestId,agent_run_id:run.data.id,requested_by:"agent",reason:"Solicitud detectada",summary:result.response.customerMessage,status:"OPEN"});const open=input.serviceRequestId?await input.db.from("human_handoffs").select("id").eq("organization_id",input.organizationId).eq("service_request_id",input.serviceRequestId).in("status",["OPEN","CLAIMED"]).limit(1):{data:[]};if(open.data?.length&&tool!=="request_handoff")throw new Error("RESPONSE_CANCELLED_BY_HANDOFF");const cost=estimateLlmCost(result.inputTokens,result.outputTokens);await input.db.from("agent_runs").update({status:tool==="request_handoff"?"HANDED_OFF":"SUCCEEDED",model:result.model,input_tokens:result.inputTokens,output_tokens:result.outputTokens,latency_ms:result.latencyMs,estimated_cost:cost,result:result.response,completed_at:new Date().toISOString()}).eq("organization_id",input.organizationId).eq("id",run.data.id);return{runId:run.data.id,result:result.response,tool,usage:{inputTokens:result.inputTokens,outputTokens:result.outputTokens,estimatedCost:cost,latencyMs:result.latencyMs}}}catch(error){await input.db.from("agent_runs").update({status:"FAILED",error_code:error instanceof Error?error.message:"UNKNOWN",completed_at:new Date().toISOString()}).eq("organization_id",input.organizationId).eq("id",run.data.id);throw error}
}