import {NextResponse} from "next/server";
import {Resend} from "resend";
import {z} from "zod";
import {getApiContext} from "@/lib/supabase/api-context";
import {createAdminClient} from "@/lib/supabase/admin";
import {consumeRateLimit} from "@/lib/rate-limit";
import {csrfError,validateMutationOrigin} from "@/lib/request-security";
import {operationalLog} from "@/lib/structured-log";
const schema=z.object({email:z.string().email().max(254),role:z.enum(["admin","agent","viewer"])});
export async function POST(request:Request){if(!validateMutationOrigin(request))return csrfError();const context=await getApiContext();if(!context)return NextResponse.json({error:"No autorizado"},{status:401});if(!["owner","admin"].includes(context.role))return NextResponse.json({error:"Permisos insuficientes"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invitación inválida"},{status:400});if(context.role==="admin"&&parsed.data.role==="admin")return NextResponse.json({error:"Un Admin no puede invitar otro Admin"},{status:403});const rate=await consumeRateLimit({scope:"organization_invite",subject:context.user.id,limit:10,windowSeconds:3600});if(!rate.allowed)return NextResponse.json({error:"Demasiadas invitaciones"},{status:429});const{data:invitationId,error}=await context.supabase.rpc("invite_member",{org:context.organizationId,invite_email:parsed.data.email,invite_role:parsed.data.role});if(error||!invitationId)return NextResponse.json({error:"No fue posible crear la invitación"},{status:400});const admin=createAdminClient();const{data:organization}=await admin.from("organizations").select("name").eq("id",context.organizationId).single();if(!process.env.RESEND_API_KEY){await admin.from("organization_invitations").delete().eq("id",invitationId);return NextResponse.json({error:"Servicio de correo no configurado"},{status:503})}const site=process.env.NEXT_PUBLIC_SITE_URL||"https://estructuradigital.cl",url=`${site}/aceptar-invitacion?id=${encodeURIComponent(String(invitationId))}`;const resend=new Resend(process.env.RESEND_API_KEY);const result=await resend.emails.send({from:process.env.CONTACT_FROM_EMAIL||"Estructura Digital <onboarding@resend.dev>",to:parsed.data.email,replyTo:process.env.CONTACT_REPLY_TO_EMAIL||"contacto@estructuradigital.cl",subject:`Invitación a ${organization?.name||"Estructura Digital"}`,text:`Te invitaron como ${parsed.data.role}. Inicia sesión y acepta la invitación: ${url}`});if(result.error){await admin.from("organization_invitations").delete().eq("id",invitationId);operationalLog("error",{organization_id:context.organizationId,user_id:context.user.id,stage:"member_invite",result:"failed",error_code:"EMAIL_REJECTED"});return NextResponse.json({error:"No fue posible enviar la invitación"},{status:502})}operationalLog("info",{organization_id:context.organizationId,user_id:context.user.id,stage:"member_invite",result:"sent"});return NextResponse.json({status:"sent"})}