"use client";
import Script from "next/script";import {useEffect,useRef,useState} from "react";import {parseMetaEmbeddedEvent,type EmbeddedAssets} from "@/lib/meta-embedded-event";
declare global{interface Window{FB?:{init(o:{appId:string;cookie:boolean;xfbml:boolean;version:string}):void;login(cb:(r:{authResponse?:{code?:string}})=>void,o:Record<string,unknown>):void}}}
type Assets=EmbeddedAssets;type Session={state:string;nonce:string;session_id:string};
export function MetaEmbeddedSignup({appId,configId,graphVersion}:{appId?:string;configId?:string;graphVersion:string}){const[ready,setReady]=useState(false),[status,setStatus]=useState("not_connected"),[message,setMessage]=useState("");const codeRef=useRef<string|undefined>(undefined),assetsRef=useRef<Assets|undefined>(undefined),sessionRef=useRef<Session|undefined>(undefined),finishingRef=useRef(false);const configured=Boolean(appId&&configId);
async function finish(){const code=codeRef.current,assets=assetsRef.current,session=sessionRef.current;if(!code||!assets||!session||finishingRef.current)return;finishingRef.current=true;setStatus("connecting");const response=await fetch("/api/meta/embedded-signup/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,...assets,...session})});const body=await response.json() as {status?:string;error?:string};setStatus(response.ok?"connected":"error");setMessage(body.error||"WhatsApp conectado y validado.");finishingRef.current=false}
useEffect(()=>{function listener(event:MessageEvent){const parsed=parseMetaEmbeddedEvent(event.origin,event.data);if(!parsed)return;if(parsed.kind==="cancel"){setStatus("not_connected");setMessage("La conexión fue cancelada.");return}if(parsed.kind==="error"){setStatus("error");setMessage("Meta informó un error durante la conexión.");return}assetsRef.current=parsed.assets;void finish()}window.addEventListener("message",listener);return()=>window.removeEventListener("message",listener)},[]);
function initialize(){if(!appId||!window.FB)return;window.FB.init({appId,cookie:true,xfbml:false,version:graphVersion});setReady(true)}
async function connect(){if(!window.FB||!configId)return;codeRef.current=undefined;assetsRef.current=undefined;sessionRef.current=undefined;finishingRef.current=false;setStatus("connecting");setMessage("Esperando autorización de Meta…");const sessionResponse=await fetch("/api/meta/embedded-signup/session",{cache:"no-store"});if(!sessionResponse.ok){setStatus("error");setMessage("No fue posible iniciar una sesión segura.");return}sessionRef.current=await sessionResponse.json() as Session;window.FB.login(response=>{const code=response.authResponse?.code;if(!code){setStatus("not_connected");setMessage("La autorización fue cancelada o no se completó.");return}codeRef.current=code;void finish()},{config_id:configId,response_type:"code",override_default_response_type:true,state:sessionRef.current.state})}
return <section className="integration-detail"><Script src="https://connect.facebook.net/es_LA/sdk.js" strategy="afterInteractive" onLoad={initialize}/><h2>Conectar cuenta empresarial</h2><p>Autoriza tus activos mediante WhatsApp Embedded Signup de Meta. Los tokens nunca llegan al navegador.</p><button id="meta-embedded-connect" className="button button-primary" type="button" onClick={connect} disabled={!configured||!ready||status==="connecting"}>{status==="connecting"?"Conectando…":"Conectar con Facebook"}</button>{!configured&&<p className="form-status">La configuración empresarial de Meta no está activa.</p>}{message&&<p className="form-status" aria-live="polite">{message}</p>}<p className="form-status">Estado: <strong>{status}</strong></p></section>}