"use server";
import { redirect } from "next/navigation"; import { createClient } from "@/lib/supabase/server"; import { isSupabaseConfigured } from "@/lib/supabase/config"; import { loginSchema, registerSchema } from "@/lib/validation/schemas";
function back(path:string,message:string):never{redirect(`${path}?error=${encodeURIComponent(message)}`)}
export async function signIn(formData:FormData){if(!isSupabaseConfigured())back("/iniciar-sesion","Supabase aún no está configurado.");const parsed=loginSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)back("/iniciar-sesion","Revisa tu correo y contraseña.");const supabase=await createClient();const{error}=await supabase.auth.signInWithPassword(parsed.data);if(error)back("/iniciar-sesion","No fue posible iniciar sesión.");redirect("/app")}
export async function signUp(formData:FormData){if(!isSupabaseConfigured())back("/registro","Supabase aún no está configurado.");const parsed=registerSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)back("/registro","Usa un correo válido y una contraseña de al menos 8 caracteres.");const supabase=await createClient();const{error}=await supabase.auth.signUp({email:parsed.data.email,password:parsed.data.password,options:{data:{full_name:parsed.data.name},emailRedirectTo:`${process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000"}/auth/callback`}});if(error)back("/registro","No fue posible crear la cuenta.");redirect("/iniciar-sesion?message=Revisa tu correo para confirmar la cuenta.")}
export async function resetPassword(formData:FormData){if(!isSupabaseConfigured())back("/recuperar-contrasena","Supabase aún no está configurado.");const email=String(formData.get("email")||"");const supabase=await createClient();const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000"}/auth/callback?next=/actualizar-contrasena`});if(error)back("/recuperar-contrasena","No fue posible procesar la solicitud.");redirect("/iniciar-sesion?message=Si el correo existe, recibirás instrucciones.")}


export async function updatePassword(formData:FormData){const password=String(formData.get("password")||"");if(password.length<12||password.length>128)back("/actualizar-contrasena","Usa una contraseña de 12 a 128 caracteres.");const supabase=await createClient();const{error}=await supabase.auth.updateUser({password});if(error)back("/actualizar-contrasena","No fue posible actualizar la contraseña.");await supabase.auth.signOut({scope:"others"});redirect("/app")};
