import {NextResponse} from "next/server";
import {z} from "zod";
import {getApiContext} from "@/lib/supabase/api-context";
import {consumeRateLimit} from "@/lib/rate-limit";
import {csrfError,validateMutationOrigin} from "@/lib/request-security";
import {operationalLog} from "@/lib/structured-log";
const target=z.string().uuid(),changeSchema=z.discriminatedUnion("action",[z.object({target,action:z.literal("change_role"),role:z.enum(["owner","admin","agent","viewer"])}),z.object({target,action:z.literal("transfer")})]),removeSchema=z.object({target});
type Context=NonNullable<Awaited<ReturnType<typeof getApiContext>>>;type AuthResult={response:NextResponse;context?:never}|{context:Context;response?:never};
async function authorized(request:Request):Promise<AuthResult>{if(!validateMutationOrigin(request))return{response:csrfError()};const context=await getApiContext();if(!context)return{response:NextResponse.json({error:"No autorizado"},{status:401})};if(!["owner","admin"].includes(context.role))return{response:NextResponse.json({error:"Permisos insuficientes"},{status:403})};const rate=await consumeRateLimit({scope:"member_admin",subject:context.user.id,limit:30,windowSeconds:3600});if(!rate.allowed)return{response:NextResponse.json({error:"Demasiados cambios"},{status:429})};return{context}}
export async function PATCH(request:Request){const auth=await authorized(request);if(auth.response)return auth.response;const parsed=changeSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Solicitud inválida"},{status:400});const{context}=auth;if(parsed.data.action==="transfer"&&context.role!=="owner")return NextResponse.json({error:"Solo Owner puede transferir"},{status:403});const rpc=parsed.data.action==="transfer"?context.supabase.rpc("transfer_ownership",{org:context.organizationId,target:parsed.data.target}):context.supabase.rpc("change_member_role",{org:context.organizationId,target:parsed.data.target,new_role:parsed.data.role});const{error}=await rpc;if(error)return NextResponse.json({error:"Cambio rechazado por política"},{status:409});operationalLog("info",{organization_id:context.organizationId,user_id:context.user.id,stage:"member_admin",result:parsed.data.action});return NextResponse.json({status:"updated"})}
export async function DELETE(request:Request){const auth=await authorized(request);if(auth.response)return auth.response;const parsed=removeSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Solicitud inválida"},{status:400});const{context}=auth;const{error}=await context.supabase.rpc("remove_member",{org:context.organizationId,target:parsed.data.target});if(error)return NextResponse.json({error:"Remoción rechazada por política"},{status:409});operationalLog("info",{organization_id:context.organizationId,user_id:context.user.id,stage:"member_admin",result:"removed"});return NextResponse.json({status:"removed"})}